[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.build]
cmds = ["pip install -r requirements.txt", "python manage.py collectstatic --noinput"]

[phases.deploy]
startCommand = "gunicorn ohres_edi.wsgi"